import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SolanaWalletProvider } from "@/Context/SolanaWalletContext";
import { UserProvider } from "@/Context/UserContext";
import Navbar from "@/Components/Navbar";
import SetUserWrapper from "@/Components/SetUserWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FundMyWork",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <SolanaWalletProvider>
          <UserProvider>
            <SetUserWrapper>
            <Navbar />
            <div className="min-h-screen pt-16">
              {children}
            </div>
            </SetUserWrapper>
          </UserProvider>
        </SolanaWalletProvider>
      </body>
    </html>
  );
}
