import { Proposal } from '@/types';

// Helper function to generate dates relative to current date
const getRelativeDate = (daysFromNow: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString();
};

export const mockProposals: Proposal[] = [
  {
    id: '1',
    proposalDetails: {
      proposalTitle: 'DeFi Dashboard for Solana Ecosystem',
      shortDescription: 'Building a comprehensive dashboard to track all DeFi activities across the Solana ecosystem, with performance metrics and portfolio management.',
      detailedDescription: 'Building a comprehensive dashboard to track all DeFi activities across the Solana ecosystem, with performance metrics and portfolio management.',
      coverImageUrl: 'https://images.pexels.com/photos/7788009/pexels-photo-7788009.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      category: 'Development',
      createdAt: new Date(getRelativeDate(-10)),
      problemStatement: 'The Solana ecosystem lacks a unified dashboard for tracking DeFi activities across different protocols.',
      tags: ['DeFi', 'Dashboard', 'Analytics', 'Portfolio'],
      demoLink: 'https://example.com/demo',
      driveLink: 'https://drive.google.com/example',
      fundUsage: 'Development costs, server expenses, and security audits.',
    },
    fundingDetails: {
      fundingGoal: 500,
      fundingReceived: 325,
      fundingDeadline: new Date(getRelativeDate(14)),
      fullyFunded: false,
      isExpired: false,
    },
    contributors: [],
    walletAddress: '8xh7...3Pdr',
  },
  {
    id: '2',
    proposalDetails: {
      proposalTitle: 'Solana NFT Generative Art Collection',
      shortDescription: 'Creating a generative art collection on Solana with 10,000 unique pieces exploring themes of digital identity.',
      detailedDescription: 'Creating a generative art collection on Solana with 10,000 unique pieces exploring themes of digital identity.',
      coverImageUrl: 'https://images.pexels.com/photos/2832382/pexels-photo-2832382.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      category: 'Art',
      createdAt: new Date(getRelativeDate(-5)),
      problemStatement: 'Need funding to complete the final algorithmic design and smart contract deployment for an innovative NFT collection.',
      tags: ['NFT', 'GenerativeArt', 'Collection'],
      fundUsage: 'Smart contract development, art engine refinement, and marketing.',
      demoLink: 'https://example.com/nft-demo',
      driveLink: 'https://drive.google.com/nft-collection',
    },
    fundingDetails: {
      fundingGoal: 200,
      fundingReceived: 75,
      fundingDeadline: new Date(getRelativeDate(5)),
      fullyFunded: false,
      isExpired: false,
    },
    contributors: [],
    walletAddress: '3jK9...m7Zq',
  },
  {
    id: '3',
    proposalDetails: {
      proposalTitle: 'Solana Developer Documentation Series',
      shortDescription: 'Writing comprehensive tutorials and documentation to help new developers build on Solana more effectively.',
      detailedDescription: 'Writing comprehensive tutorials and documentation to help new developers build on Solana more effectively.',
      coverImageUrl: 'https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      category: 'Content',
      createdAt: new Date(getRelativeDate(-20)),
      problemStatement: 'Current documentation is scattered and often too technical for newcomers to understand.',
      tags: ['Documentation', 'Tutorials', 'Education'],
      fundUsage: 'Content creation, editing, and platform hosting.',
      demoLink: 'https://example.com/sample',
      driveLink: 'https://drive.google.com/docs',
    },
    fundingDetails: {
      fundingGoal: 150,
      fundingReceived: 150,
      fundingDeadline: new Date(getRelativeDate(30)),
      fullyFunded: true,
      isExpired: false,
    },
    contributors: [],
    walletAddress: '5tGH...9Uvx',
  },
  {
    id: '4',
    proposalDetails: {
      proposalTitle: 'Solana SPL Token Analytics Research',
      shortDescription: 'Conducting in-depth research on SPL token economics, usage patterns, and market dynamics on Solana.',
      detailedDescription: 'Conducting in-depth research on SPL token economics, usage patterns, and market dynamics on Solana.',
      coverImageUrl: 'https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      category: 'Research',
      createdAt: new Date(getRelativeDate(-15)),
      problemStatement: 'There is limited analytical data about SPL token behavior and economics on Solana.',
      tags: ['Research', 'Analytics', 'TokenEconomics', 'DataScience'],
      fundUsage: 'Data collection tools, statistical analysis, and report publishing.',
      driveLink: 'https://drive.google.com/example2',
      demoLink: 'https://example.com/token-analytics',
    },
    fundingDetails: {
      fundingGoal: 350,
      fundingReceived: 120,
      fundingDeadline: new Date(getRelativeDate(21)),
      fullyFunded: false,
      isExpired: false,
    },
    contributors: [],
    walletAddress: '7pQd...2Rxz',
  },
  {
    id: '5',
    proposalDetails: {
      proposalTitle: 'Solana Community Events Platform',
      shortDescription: 'Building a dedicated platform for organizing and discovering Solana community events, hackathons, and meetups worldwide.',
      detailedDescription: 'Building a dedicated platform for organizing and discovering Solana community events, hackathons, and meetups worldwide.',
      coverImageUrl: 'https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      category: 'Community',
      createdAt: new Date(getRelativeDate(-8)),
      problemStatement: 'Community events for Solana are difficult to discover and track across different platforms.',
      tags: ['Community', 'Events', 'Platform', 'Meetups'],
      fundUsage: 'Platform development, community moderation tools, and initial marketing.',
      demoLink: 'https://example.com/events-platform',
      driveLink: 'https://drive.google.com/events',
    },
    fundingDetails: {
      fundingGoal: 280,
      fundingReceived: 50,
      fundingDeadline: new Date(getRelativeDate(10)),
      fullyFunded: false,
      isExpired: false,
    },
    contributors: [],
    walletAddress: '2cNm...8Tgb',
  },
  {
    id: '6',
    proposalDetails: {
      proposalTitle: 'Solana Indexer Optimization',
      shortDescription: 'Optimizing the performance of Solana indexers to improve data retrieval times for dApps and services.',
      detailedDescription: 'Optimizing the performance of Solana indexers to improve data retrieval times for dApps and services.',
      coverImageUrl: 'https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
      category: 'Development',
      createdAt: new Date(getRelativeDate(-12)),
      problemStatement: 'Current indexing solutions for Solana have performance bottlenecks that limit dApp capabilities.',
      tags: ['Indexer', 'Performance', 'Infrastructure', 'DataAccess'],
      fundUsage: 'Development resources, performance testing, and documentation.',
      demoLink: 'https://example.com/indexer-demo',
      driveLink: 'https://drive.google.com/indexer',
    },
    fundingDetails: {
      fundingGoal: 400,
      fundingReceived: 230,
      fundingDeadline: new Date(getRelativeDate(25)),
      fullyFunded: false,
      isExpired: false,
    },
    contributors: [],
    walletAddress: '4jPr...7Kfn',
  },
];